name: C/C++ CI

on: [push]
jobs:
  build_gcc:
    name: Ubuntu GCC build and unit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Install Boost
      run:  sudo apt install libboost-all-dev
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run:  cmake . 
    - name: Build
      run:  make -j 8
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test

  build_clang:
    name: MacOS Clang build and unit tests
    runs-on: macOS-latest
    steps:
    - name: Install Boost
      run:  brew install boost
    - name: Clone repo
      uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Configure
      run:  cmake .
    - name: Build
      run:  make -j 8
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test
