name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: configure
      run: cmake -DBOOST_ROOT=$BOOST_ROOT .
    - name: make
      run: make
    - name: make test
      run: make test
