name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
   
    steps:
    - uses: actions/checkout@v1 actions/checkout-submodules@v2
    - name: cmake
      run: cmake -DBOOST_ROOT=${BOOST_ROOT} . 
    - name: make
      run: make
    - name: make test
      run: env CTEST_OUTPUT_ON_FAILURE=1 make test

