name: C/C++ CI

on: [push]
jobs:
  build_gcc:
    name: Ubuntu GCC build and unit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Install Boost
      run:  sudo apt install libboost-all-dev
    - name: Install lcov
      run:  sudo apt install lcov
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run:  cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .
    - name: Build
      run:  make -j $(nproc)
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test
    - name: Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: ./coverage.sh

  build_clang:
    name: MacOS Clang build and unit tests
    runs-on: macOS-latest
    steps:
    - name: Install Boost
      run:  brew install boost
    - name: Clone repo
      uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Configure
      run:  cmake .
    - name: Build
      run:  make -j $(nproc)
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test
